variables:
  BuildNumber: $[counter('CustomBuildNumber', 0)]
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    BranchName: ''
  ${{ if ne( variables['Build.SourceBranchName'], 'master') }}:
    BranchName: -${{ variables['Build.SourceBranchName'] }}
  artifact_name: StaticWebsite

name: $(BuildNumber)$(BranchName)

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - template: .azure-pipelines/npm-restore.yml
    - template: .azure-pipelines/npm-build.yml
    - template: .azure-pipelines/add-robots.yml
    - template: .azure-pipelines/publish-artifact.yml
