steps:
- task: NodeTool@0
  displayName: 'Install Node.js'
  inputs:
    versionSpec: '12.x'

- task: Npm@1
  displayName: 'Install NPM Dependencies'
  inputs:
    verbose: false
    command: install
